/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaMilenaRouteImport } from './routes/ajuda-milena'
import { Route as EscreverCartaRouteImport } from './routes/escrever-carta'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as UpsellRouteImport } from './routes/upsell'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaMilenaRoute = AjudaMilenaRouteImport.update({
  id: '/ajuda-milena',
  path: '/ajuda-milena',
  getParentRoute: () => rootRouteImport,
} as any)
const EscreverCartaRoute = EscreverCartaRouteImport.update({
  id: '/escrever-carta',
  path: '/escrever-carta',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda-milena': typeof AjudaMilenaRoute
  '/escrever-carta': typeof EscreverCartaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/upsell': typeof UpsellRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda-milena': typeof AjudaMilenaRoute
  '/escrever-carta': typeof EscreverCartaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/upsell': typeof UpsellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda-milena': typeof AjudaMilenaRoute
  '/escrever-carta': typeof EscreverCartaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/upsell': typeof UpsellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda-milena'
    | '/escrever-carta'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/upsell'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda-milena'
    | '/escrever-carta'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/upsell'
  id:
    | '__root__'
    | '/'
    | '/ajuda-milena'
    | '/escrever-carta'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/upsell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaMilenaRoute: typeof AjudaMilenaRoute
  EscreverCartaRoute: typeof EscreverCartaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  UpsellRoute: typeof UpsellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda-milena': {
      id: '/ajuda-milena'
      path: '/ajuda-milena'
      fullPath: '/ajuda-milena'
      preLoaderRoute: typeof AjudaMilenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrever-carta': {
      id: '/escrever-carta'
      path: '/escrever-carta'
      fullPath: '/escrever-carta'
      preLoaderRoute: typeof EscreverCartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaMilenaRoute: AjudaMilenaRoute,
  EscreverCartaRoute: EscreverCartaRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  UpsellRoute: UpsellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
