/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaMilenaRouteImport } from './routes/ajuda-milena'
import { Route as ApoioMilenaRouteImport } from './routes/apoio-milena'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EscreverCartaRouteImport } from './routes/escrever-carta'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VisaoGeralRouteImport } from './routes/visao-geral'
import { Route as Visao_geralRouteImport } from './routes/visao_geral'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaMilenaRoute = AjudaMilenaRouteImport.update({
  id: '/ajuda-milena',
  path: '/ajuda-milena',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioMilenaRoute = ApoioMilenaRouteImport.update({
  id: '/apoio-milena',
  path: '/apoio-milena',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EscreverCartaRoute = EscreverCartaRouteImport.update({
  id: '/escrever-carta',
  path: '/escrever-carta',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaoGeralRoute = VisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const Visao_geralRoute = Visao_geralRouteImport.update({
  id: '/visao_geral',
  path: '/visao_geral',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda-milena': typeof AjudaMilenaRoute
  '/apoio-milena': typeof ApoioMilenaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/dashboard': typeof DashboardRoute
  '/escrever-carta': typeof EscreverCartaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/visao-geral': typeof VisaoGeralRoute
  '/visao_geral': typeof Visao_geralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda-milena': typeof AjudaMilenaRoute
  '/apoio-milena': typeof ApoioMilenaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/dashboard': typeof DashboardRoute
  '/escrever-carta': typeof EscreverCartaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/visao-geral': typeof VisaoGeralRoute
  '/visao_geral': typeof Visao_geralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda-milena': typeof AjudaMilenaRoute
  '/apoio-milena': typeof ApoioMilenaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/dashboard': typeof DashboardRoute
  '/escrever-carta': typeof EscreverCartaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/visao-geral': typeof VisaoGeralRoute
  '/visao_geral': typeof Visao_geralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda-milena'
    | '/apoio-milena'
    | '/como-funciona'
    | '/dashboard'
    | '/escrever-carta'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/visao-geral'
    | '/visao_geral'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda-milena'
    | '/apoio-milena'
    | '/como-funciona'
    | '/dashboard'
    | '/escrever-carta'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/visao-geral'
    | '/visao_geral'
  id:
    | '__root__'
    | '/'
    | '/ajuda-milena'
    | '/apoio-milena'
    | '/como-funciona'
    | '/dashboard'
    | '/escrever-carta'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/visao-geral'
    | '/visao_geral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaMilenaRoute: typeof AjudaMilenaRoute
  ApoioMilenaRoute: typeof ApoioMilenaRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  DashboardRoute: typeof DashboardRoute
  EscreverCartaRoute: typeof EscreverCartaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  VisaoGeralRoute: typeof VisaoGeralRoute
  Visao_geralRoute: typeof Visao_geralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda-milena': {
      id: '/ajuda-milena'
      path: '/ajuda-milena'
      fullPath: '/ajuda-milena'
      preLoaderRoute: typeof AjudaMilenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio-milena': {
      id: '/apoio-milena'
      path: '/apoio-milena'
      fullPath: '/apoio-milena'
      preLoaderRoute: typeof ApoioMilenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrever-carta': {
      id: '/escrever-carta'
      path: '/escrever-carta'
      fullPath: '/escrever-carta'
      preLoaderRoute: typeof EscreverCartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visao-geral': {
      id: '/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof VisaoGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visao_geral': {
      id: '/visao_geral'
      path: '/visao_geral'
      fullPath: '/visao_geral'
      preLoaderRoute: typeof Visao_geralRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaMilenaRoute: AjudaMilenaRoute,
  ApoioMilenaRoute: ApoioMilenaRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  DashboardRoute: DashboardRoute,
  EscreverCartaRoute: EscreverCartaRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  VisaoGeralRoute: VisaoGeralRoute,
  Visao_geralRoute: Visao_geralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
