create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_type text not null,
  page text,
  title text,
  step text,
  label text,
  value text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  user_agent text,
  client_ip inet,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists analytics_events_session_id_idx
  on public.analytics_events (session_id);
create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

alter table public.analytics_events enable row level security;

drop policy if exists "service_role_manage_analytics_events" on public.analytics_events;
create policy "service_role_manage_analytics_events"
  on public.analytics_events
  for all
  to service_role
  using (true)
  with check (true);
